version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres15
    restart: always  # Контейнер будет перезапускаться при сбоях или перезагрузке хоста
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: qna_db
    ports:
      - "5435:5432"  # Пробрасываем порт для доступа к базе данных
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Монтируем данные базы данных в volume

  app:
    build: .  # Сборка образа из текущей директории, где лежит Dockerfile
    container_name: qna-fastapi
    restart: unless-stopped  # Контейнер будет перезапускаться, если не был остановлен вручную
    ports:
      - "8000:8000"  # Пробрасываем порт для доступа к приложению
    volumes:
      - ./app:/app/app  # Монтируем локальную папку ./app в /app/app контейнера

volumes:
  postgres_data:  # Определяем volume для хранения данных базы данных
